### ISSUE TITLE
Additional features required welcome video 

### ISSUE THREAD

**Issue by mani2care** [dan-snelson/dialog-scripts#42] opened 2023-02-24 16:45 UTC
Hi Team 

welcomeDialog="${6:-"true"}"                                                # [ true (default) | false ]

Instead of welcome dialog can we add additional welcome video so it’s easier user can understand the company vision and mission with muted so user can unmute and watch the video meme time install will be completed in back end 🤔 if possible to add multiple video & randomising so everyone time enroll user will feel new innovative content about organisation 🎉

**Comment by mani2care** [comment] 2023-02-24 16:52
Second idea is 

if above idea not works then we can add it instead of imange can we add bannervideo while first execution latese if user want they can unmute watch the video about organisation men time all the installing will be done in background 

![Uploading EB85339C-559C-497E-B6F1-9627DE5E33D9.jpeg…]()

**Comment by dan-snelson** [comment] 2023-02-24 16:55
Closing as a duplicate of Issue #36.

**Closed by dan-snelson** 2023-02-24 16:55 UTC
Labels: enhancement
